CREATE TABLE Role
(
  ID INT NOT NULL,
  RoleName VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE Users
(
  E_mail VARCHAR(100) NOT NULL,
  Password CHAR(60) NOT NULL,
  Username VARCHAR(50) NOT NULL,
  ID INT NOT NULL,
  ProfilePicture VARCHAR(100) NOT NULL,
  IsBanned INT NOT NULL,
  RoleID INT NOT NULL,
  IsConfirmed BOOLEAN NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (RoleID) REFERENCES Role(ID)
);

CREATE TABLE Recipe
(
  CoverPicture VARCHAR(100) NOT NULL,
  RecipeName VARCHAR(50) NOT NULL,
  Description VARCHAR(500) NOT NULL,
  ID INT NOT NULL,
  IsApprooved BOOLEAN NOT NULL,
  CookingDuration INT NOT NULL,
  UserID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (UserID) REFERENCES Users(ID)
);

CREATE TABLE RecipeStep
(
  ID INT NOT NULL,
  StepDescription VARCHAR(500) NOT NULL,
  OrderNumber INT NOT NULL,
  RecipeID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (RecipeID) REFERENCES Recipe(ID)
);

CREATE TABLE Image
(
  ID INT NOT NULL,
  OrderNumber INT NOT NULL,
  Link VARCHAR(100) NOT NULL,
  RecipeID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (RecipeID) REFERENCES Recipe(ID)
);

CREATE TABLE Ingredient
(
  ID INT NOT NULL,
  IngredientName VARCHAR(50) NOT NULL,
  Quantity INT NOT NULL,
  Measure VARCHAR(50) NOT NULL,
  RecipeID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (RecipeID) REFERENCES Recipe(ID)
);

CREATE TABLE Video
(
  ID INT NOT NULL,
  OrderNumber INT NOT NULL,
  Link VARCHAR(100) NOT NULL,
  RecipeID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (RecipeID) REFERENCES Recipe(ID)
);

CREATE TABLE Favorite
(
  UserID INT NOT NULL,
  RecipeID INT NOT NULL,
  PRIMARY KEY (UserID, RecipeID),
  FOREIGN KEY (UserID) REFERENCES Users(ID),
  FOREIGN KEY (RecipeID) REFERENCES Recipe(ID)
);

CREATE TABLE Rating
(
  RatingValue INT NOT NULL,
  UserID INT NOT NULL,
  RecipeID INT NOT NULL,
  PRIMARY KEY (UserID, RecipeID),
  FOREIGN KEY (UserID) REFERENCES Users(ID),
  FOREIGN KEY (RecipeID) REFERENCES Recipe(ID)
);

CREATE TABLE Comments
(
  CommentText VARCHAR(200) NOT NULL,
  UserID INT NOT NULL,
  RecipeID INT NOT NULL,
  PRIMARY KEY (UserID, RecipeID),
  FOREIGN KEY (UserID) REFERENCES Users(ID),
  FOREIGN KEY (RecipeID) REFERENCES Recipe(ID)
);