name: CI
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy_backend:
    name: Build jar and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Generate deployment package
        working-directory: ./backend/zavrsni_rad
        run: mvn clean package
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          wait_for_environment_recovery: 60
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: zavrsni_rad
          environment_name: Zavrsnirad-env
          version_label: ${{ github.run_number }}
          region: us-east-1
          deployment_package: backend/zavrsni_rad/target/zavrsni_rad-0.0.1-SNAPSHOT.zip

  build_appbundle:
    name: Build Flutter (Android)
    working-directory: ./frontend/zavrsni_rad
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "frontend/zavrsni_rad/build/app/outputs/apk/release/*"
          tag: v1.0.${{ github.run_number }}